name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: matrix
      run: |
        echo "value=[\"a\", \"b\", \"c\"]" >> $GITHUB_OUTPUT
    - run: |
        echo "${{ steps.matrix.outputs.value }}"
    # - name: Print to Log
    #   id: print-to-log
    #   uses: actions/hello-world-javascript-action@main
    #   with:
    #     who-to-greet: ${{ matrix.value }}



